<?php
$bd = array(
	'type'=>array(
		'integrationWeb'=>'Intégration Web',
		'programmation'=>'Programmation',
		'divers'=>'Divers',
	),
	'project'=>array(
		// l'ordre des projets =  ordre dans le caroussel accueil
		'plaisirsSucres'=>array(
			'title'=>'Plaisirs Sucrés',
			'link'=>'http://etudiant-tim.cstj.qc.ca/1056981/plaisirs_sucres/',
			'date'=>'Hiver 2017',
			'mandat'=>'Le mandat était de produire un site web pour la compagnie fictive "plaisirs sucrés" utilisant seulement le matériel fourni par le professeur/client. Il fallait faire la page d\'accueil, la liste des cupcakes ainsi que la page de choco-noisette',
			'raison'=>'Ce projet vous démontre ma capacité à produire un site web à commencer par les maquettes Photoshop jusqu\'à l\'intégration tout en suivant un échéancier strict.',
			'sources'=>array('Les images ont été fournies par le professeur'),
			'technologies'=>'Photoshop, Illustrator, HTML, CSS, JavaScript, SASS, Bootstrap',
			'type'=>'integrationWeb',
			'github'=>'true',
			'hint'=>'Html/Css',
		),
		// 'guideTv'=>array(
		// 	'title'=>'Guide Tv',
		// 	'link'=>'http://etudiant-tim.cstj.qc.ca/1056981/guidetv/',
		// 	'date'=>'Automne 2016',
		// 	'mandat'=>'Le mandat était de produire le prototype d\'une WebApp permettant de regarder des séries, garder en mémoire les favories ainsi que les épisodes écoutés. Ce WebApp devait absolument être responsive à 100%.',
		// 	'raison'=>'Ce projet démontre ma capacité à produire une interface à partir d\'une liste de besoins.',
		// 	'sources'=>array('Les images ont été fournies par le professeur'),
		// 	'technologies'=>'HTML, CSS, JavaScript, SASS, Bootstrap, JQuerry',
		// 	'type'=>'integrationWeb',
		// 	'github'=>'false',
		// 	'hint'=>'Html/Css/Js',
		// ),
		'recettesExtremes'=>array(
			'title'=>'Recettes Extrêmes',
			'link'=>'http://etudiant-tim.cstj.qc.ca/1056981/recettesExtremes/',
			'date'=>'Hiver 2017',
			'mandat'=>'Pour ce projet, le mandat était de rendre le site "recettes extrêmes" dynamique en générant le html à l\'aide de classes et de php.',
			'raison'=>'J\'ai choisi ce projet, car il démontre bien ma capacité à produire du code simple et compréhensible dans le but de facilité la production d\'un projet.',
			'sources'=>array('Les images ont été fournies par le professeur'),
			'technologies'=>'HTML, PHP',
			'type'=>'integrationWeb',
			'github'=>'true',
			'hint'=>'PHP',
		),
		'infiltrateur'=>array(
			'title'=>'L\'infiltrateur',
			'link'=>'http://etudiant-tim.cstj.qc.ca/1056981/infiltrateur',
			'date'=>'Hiver 2018',
			'mandat'=>'Ce projet a été fait durant le gamejam de Valleyfield du 16 au 18 janvier 2018. Nous avions 48 heures pour produire un jeu sous le thème de l\'espionnage. Nous étions une équipe de 8 personnes à participer à cet événement',
			'raison'=>'Dans ce projet d\'équipe, je me suis occupé de la programmation du personnage, des dialogues ainsi que les différents bogues trouvés lors de la production.',
			'sources'=>array(),
			'technologies'=>'Unity, C#',
			'type'=>'programmation',
			'github'=>'false',
			'hint'=>'Gamejam - Unity',
		),
		'balloonVsNinja'=>array(
			'title'=>'Balloon vs Ninja',
			'link'=>'http://etudiant-tim.cstj.qc.ca/1056981/balloonVsNinja/balloonVsNinja.html',
			'date'=>'Automne 2016',
			'mandat'=>'Le mandat de ce projet était de faire un jeu au choix où on y retrouve des projectiles générés aléatoirement, un système de pointage, ainsi qu\'un système de vie.',
			'raison'=>'Pour ce projet, le professeur proposait un jeu de type "scrolling shooter". J\'ai su me démarquer en produisant un jeu unique tout en respectant chacune des demandes du devis.',
			'sources'=>array('Sons générés avec sfxr - sound effect generator'),
			'technologies'=>'Animate, Action Script 3',
			'type'=>'programmation',
			'github'=>'true',
			'hint'=>'ActionScript',
		),
		'escapeTheRoom'=>array(
			'title'=>'Escape the room',
			'link'=>'http://etudiant-tim.cstj.qc.ca/1056981/escapeTheRoom',
			'date'=>'Automne 2017',
			'mandat'=>'Le mandat de ce projet était de faire un jeu de type labyrinthe où il faut 2 étapes pour terminer le jeu',
			'raison'=>'Ce projet démontre bien la maitrise de méthodes MonoBehaviour, les animations, les changements de scènes ainsi que les concepts de base du logiciel Unity.',
			'sources'=>array(''),
			'technologies'=>'Unity, C#',
			'type'=>'programmation',
			'github'=>'true',
			'hint'=>'Unity - C#',
		),
		'lAbrisDeMeon'=>array(
			'title'=>'L\'Abris de Méon',
			'video'=>'<iframe width="100%" height="100%" src="https://www.youtube.com/embed/T_AW06eToxM?ecver=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>',
			'date'=>'Automne 2017',
			'mandat'=>'Le mandat de ce projet était de concevoir un jeu ayant une balance entre le "fun", "flow" et "functionnalities". Il fallait présenter ce concept à l\'aide d\'une vidéo montrant la jouabilité d\'un niveau.',
			'raison'=>'Chaque petit élément ajouté dans cette vidéo démontre bien mon souci du détail. De plus, ce concept original démontre que j\'ai de bonnes idées innovatrices permettant distingué un projet de ses concurrents!',
			'technologies'=>'Animate, Audition, Premiere',
			'type'=>'divers',
			'hint'=>'Conception d\'un jeu'
		),
		'laventureDuPompier'=>array(
			'title'=>'L\'Aventure Du Pompier',
			'date'=>'Hiver 2015',
			'mandat'=>'Le mandat de ce projet était de reproduire les effets visuels d\'une affiche en utilisant un thème différent.',
			'raison'=>'Ce projet démontre mon aisance avec le logiciel Photoshop. Je maitrise bien l\'utilisation des filtres et calques de fusion dans le but de reproduire un thème visuel déjà existant.',
			'sources'=>array(
				'Extincteur - https://pixabay.com/static/uploads/photo/2013/07/18/15/09/fire-164768_960_720.jpg',
				'Rayures - https://inspirationhive.com/wp-content/uploads/2012/07/Scratches1-500x666.jpg ',
				'Taches - https://pixabay.com/static/uploads/photo/2014/04/04/14/55/paper-313369_960_720.jpg',
				'Nuage#1 - http://a406.idata.over-blog.com/600x400/3/04/65/21/Mars-2013/10.03.13-promenade-dans-les-bois/recette/bonheur-9.jpg',
				'Nuage#2 - http://www.fotorevista.com.ar/SFotos/14/10/09/141009000315g.jpg',
				'Nuage#3 - http://1.bp.blogspot.com/-78T2ETBlQDs/T4rJdKGJCaI/AAAAAAAABXY/1shq1iexL98/s640/nimbus.jpg',
			),
			'technologies'=>'Photoshop',
			'type'=>'divers',
			'imageModele'=>'laventureDuPompier_model.jpg',
			'etapes'=>array(
				//code brut: projetDesign.php
				'0'=>'laventureDuPompier_0.jpg',
				'1'=>'laventureDuPompier_1.jpg',
				'2'=>'laventureDuPompier_2.jpg',
				'3'=>'laventureDuPompier_3.jpg',
				'4'=>'laventureDuPompier_4.jpg',
				'5'=>'laventureDuPompier_5.jpg',
			),
			'hint'=>'Techniques Photoshop'
		),
	),
);
?>
